### ISSUE TITLE
Will other form of mermaid graphics be supported, besides gantt.

### ISSUE THREAD

**Issue by y9c** [threeq/hexo-tag-gantt#1]
hexo-tag-gantt是不是只能支持gantt图, 其他形式的mermaid语法能够解析么?
如果没有, 会不会有考虑添加?

**Comment by threeq** [comment]
目前只支持gantt图，后面有打算支持Flowcharts，这个会单独开一个工程
但是对于Sequence图，没有打算支持。
因为已经有一个 hexo-tag-plantuml 这个插件了，里面用的plantuml语法，可以支持所有的uml图。

**Comment by y9c** [comment]
这样子为什么不直接开发一个hexo-tag-mermaid呢

目前好像只有jekyll有这样的插件。

**Comment by y9c** [comment]
还有就是安装后解析失败

```
TypeError: path is required!

```

**Comment by threeq** [comment]
输出的具体日志贴出来看一下！还有就是你那边现在使用的版本信息！

**Comment by threeq** [comment]
如果都都写在一个版本库里面，一个版本库里面的功能就会比较多了！
同时以后如果需要更换底层实现就会很麻烦了
不过如果只考虑把 mermaid 的所有图形封装成一个hexo插件，这样做是可以的

**Comment by y9c** [comment]
找到了一个能完美支持的库, 不过不是hexo的, 不知道可不可以借鉴
tylingsoft/markdown-plus
